import { Component } from '@angular/core';
import { Documents } from '../models/documents';

@Component({
  selector: 'app-documents-table',
  templateUrl: './documents-table.component.html',
  styleUrls: ['./documents-table.component.scss']
})
export class DocumentsTableComponent {
  nivelNacional: Array<Documents> = [
    new Documents("2022","Segunda Vuelta","Elección de Presidente y Vicepresidente", "19 de junio", "https://registraduriaco.sharepoint.com/:b:/s/DireccindeGestinElectoral209/EdER1-WGQHpMtCikZWFtlrwBFWbJcN7vnaw8CQ2uLNxTdA?e=pef4zw", "ACTA GENERAL DEL ESCRUTINIO (AGE)", "https://registraduriaco.sharepoint.com/:b:/s/DireccindeGestinElectoral209/ERJjblt82wpHo3fMYKdzt3wBdCuYaAqZwFor1RaEEZ496A?e=Nn5heS", "ACTA DEL ESCRUTINIO GENERAL (E-26)", "https://registraduriaco.sharepoint.com/:b:/s/DireccindeGestinElectoral209/EQqWWjF6Rf5Ev6jH2AiKab0Bri7g41kz2Qp93AYwaGsI-Q?e=gMIH4g", "RESULTADOS DEL ESCRUTIONO (E-24)", "https://registraduriaco.sharepoint.com/:b:/s/DireccindeGestinElectoral209/EZEhLd64cOVMmKOazm9XIigBdlBj0SQ9vOTW_olYzVjOug?e=WUJ8FC", "ACUERDOS", "https://registraduriaco.sharepoint.com/:x:/s/DireccindeGestinElectoral209/EW4SfksUAR9Pqa55ldX2i2YBB1MtZniUlr9oSwFe8xxXNg?e=feQMi1", "DATA PROCESO ELECTORAL"), 
    new Documents("2022","Segunda Vuelta","Elección de Presidente y Vicepresidente", "29 de junio", "https://registraduriaco.sharepoint.com/:b:/s/DireccindeGestinElectoral209/EdER1-WGQHpMtCikZWFtlrwBFWbJcN7vnaw8CQ2uLNxTdA?e=pef4zw", "ACTA GENERAL DEL ESCRUTINIO (AGE)", "https://registraduriaco.sharepoint.com/:b:/s/DireccindeGestinElectoral209/ERJjblt82wpHo3fMYKdzt3wBdCuYaAqZwFor1RaEEZ496A?e=Nn5heS", "ACTA DEL ESCRUTINIO GENERAL (E-26)", "https://registraduriaco.sharepoint.com/:b:/s/DireccindeGestinElectoral209/EQqWWjF6Rf5Ev6jH2AiKab0Bri7g41kz2Qp93AYwaGsI-Q?e=gMIH4g", "RESULTADOS DEL ESCRUTIONO (E-24)", "", "-", "https://registraduriaco.sharepoint.com/:x:/s/DireccindeGestinElectoral209/EW4SfksUAR9Pqa55ldX2i2YBB1MtZniUlr9oSwFe8xxXNg?e=feQMi1", "DATA PROCESO ELECTORAL"),
    new Documents("2022","Segunda Vuelta","Elección de Presidente y Vicepresidente", "29 de junio", "https://registraduriaco.sharepoint.com/:b:/s/DireccindeGestinElectoral209/EdER1-WGQHpMtCikZWFtlrwBFWbJcN7vnaw8CQ2uLNxTdA?e=pef4zw", "ACTA GENERAL DEL ESCRUTINIO (AGE)", "https://registraduriaco.sharepoint.com/:b:/s/DireccindeGestinElectoral209/ERJjblt82wpHo3fMYKdzt3wBdCuYaAqZwFor1RaEEZ496A?e=Nn5heS", "ACTA DEL ESCRUTINIO GENERAL (E-26)", "https://registraduriaco.sharepoint.com/:b:/s/DireccindeGestinElectoral209/EQqWWjF6Rf5Ev6jH2AiKab0Bri7g41kz2Qp93AYwaGsI-Q?e=gMIH4g", "RESULTADOS DEL ESCRUTIONO (E-24)", "", "-", "https://registraduriaco.sharepoint.com/:x:/s/DireccindeGestinElectoral209/EW4SfksUAR9Pqa55ldX2i2YBB1MtZniUlr9oSwFe8xxXNg?e=feQMi1", "DATA PROCESO ELECTORAL"),
    new Documents("2022","Segunda Vuelta","Elección de Presidente y Vicepresidente", "29 de junio", "https://registraduriaco.sharepoint.com/:b:/s/DireccindeGestinElectoral209/EdER1-WGQHpMtCikZWFtlrwBFWbJcN7vnaw8CQ2uLNxTdA?e=pef4zw", "ACTA GENERAL DEL ESCRUTINIO (AGE)", "https://registraduriaco.sharepoint.com/:b:/s/DireccindeGestinElectoral209/ERJjblt82wpHo3fMYKdzt3wBdCuYaAqZwFor1RaEEZ496A?e=Nn5heS", "ACTA DEL ESCRUTINIO GENERAL (E-26)", "https://registraduriaco.sharepoint.com/:b:/s/DireccindeGestinElectoral209/EQqWWjF6Rf5Ev6jH2AiKab0Bri7g41kz2Qp93AYwaGsI-Q?e=gMIH4g", "RESULTADOS DEL ESCRUTIONO (E-24)", "", "-", "https://registraduriaco.sharepoint.com/:x:/s/DireccindeGestinElectoral209/EW4SfksUAR9Pqa55ldX2i2YBB1MtZniUlr9oSwFe8xxXNg?e=feQMi1", "DATA PROCESO ELECTORAL"),
    new Documents("2022","Segunda Vuelta","Elección de Presidente y Vicepresidente", "29 de junio", "https://registraduriaco.sharepoint.com/:b:/s/DireccindeGestinElectoral209/EdER1-WGQHpMtCikZWFtlrwBFWbJcN7vnaw8CQ2uLNxTdA?e=pef4zw", "ACTA GENERAL DEL ESCRUTINIO (AGE)", "https://registraduriaco.sharepoint.com/:b:/s/DireccindeGestinElectoral209/ERJjblt82wpHo3fMYKdzt3wBdCuYaAqZwFor1RaEEZ496A?e=Nn5heS", "ACTA DEL ESCRUTINIO GENERAL (E-26)", "https://registraduriaco.sharepoint.com/:b:/s/DireccindeGestinElectoral209/EQqWWjF6Rf5Ev6jH2AiKab0Bri7g41kz2Qp93AYwaGsI-Q?e=gMIH4g", "RESULTADOS DEL ESCRUTIONO (E-24)", "", "-", "https://registraduriaco.sharepoint.com/:x:/s/DireccindeGestinElectoral209/EW4SfksUAR9Pqa55ldX2i2YBB1MtZniUlr9oSwFe8xxXNg?e=feQMi1", "DATA PROCESO ELECTORAL"),
    new Documents("2022","Segunda Vuelta","Elección de Presidente y Vicepresidente", "29 de junio", "https://registraduriaco.sharepoint.com/:b:/s/DireccindeGestinElectoral209/EdER1-WGQHpMtCikZWFtlrwBFWbJcN7vnaw8CQ2uLNxTdA?e=pef4zw", "ACTA GENERAL DEL ESCRUTINIO (AGE)", "https://registraduriaco.sharepoint.com/:b:/s/DireccindeGestinElectoral209/ERJjblt82wpHo3fMYKdzt3wBdCuYaAqZwFor1RaEEZ496A?e=Nn5heS", "ACTA DEL ESCRUTINIO GENERAL (E-26)", "https://registraduriaco.sharepoint.com/:b:/s/DireccindeGestinElectoral209/EQqWWjF6Rf5Ev6jH2AiKab0Bri7g41kz2Qp93AYwaGsI-Q?e=gMIH4g", "RESULTADOS DEL ESCRUTIONO (E-24)", "", "-", "https://registraduriaco.sharepoint.com/:x:/s/DireccindeGestinElectoral209/EW4SfksUAR9Pqa55ldX2i2YBB1MtZniUlr9oSwFe8xxXNg?e=feQMi1", "DATA PROCESO ELECTORAL"),
    new Documents("2022","Segunda Vuelta","Elección de Presidente y Vicepresidente", "29 de junio", "https://registraduriaco.sharepoint.com/:b:/s/DireccindeGestinElectoral209/EdER1-WGQHpMtCikZWFtlrwBFWbJcN7vnaw8CQ2uLNxTdA?e=pef4zw", "ACTA GENERAL DEL ESCRUTINIO (AGE)", "https://registraduriaco.sharepoint.com/:b:/s/DireccindeGestinElectoral209/ERJjblt82wpHo3fMYKdzt3wBdCuYaAqZwFor1RaEEZ496A?e=Nn5heS", "ACTA DEL ESCRUTINIO GENERAL (E-26)", "https://registraduriaco.sharepoint.com/:b:/s/DireccindeGestinElectoral209/EQqWWjF6Rf5Ev6jH2AiKab0Bri7g41kz2Qp93AYwaGsI-Q?e=gMIH4g", "RESULTADOS DEL ESCRUTIONO (E-24)", "", "-", "https://registraduriaco.sharepoint.com/:x:/s/DireccindeGestinElectoral209/EW4SfksUAR9Pqa55ldX2i2YBB1MtZniUlr9oSwFe8xxXNg?e=feQMi1", "DATA PROCESO ELECTORAL"),
    new Documents("2022","Segunda Vuelta","Elección de Presidente y Vicepresidente", "29 de junio", "https://registraduriaco.sharepoint.com/:b:/s/DireccindeGestinElectoral209/EdER1-WGQHpMtCikZWFtlrwBFWbJcN7vnaw8CQ2uLNxTdA?e=pef4zw", "ACTA GENERAL DEL ESCRUTINIO (AGE)", "https://registraduriaco.sharepoint.com/:b:/s/DireccindeGestinElectoral209/ERJjblt82wpHo3fMYKdzt3wBdCuYaAqZwFor1RaEEZ496A?e=Nn5heS", "ACTA DEL ESCRUTINIO GENERAL (E-26)", "https://registraduriaco.sharepoint.com/:b:/s/DireccindeGestinElectoral209/EQqWWjF6Rf5Ev6jH2AiKab0Bri7g41kz2Qp93AYwaGsI-Q?e=gMIH4g", "RESULTADOS DEL ESCRUTIONO (E-24)", "", "-", "https://registraduriaco.sharepoint.com/:x:/s/DireccindeGestinElectoral209/EW4SfksUAR9Pqa55ldX2i2YBB1MtZniUlr9oSwFe8xxXNg?e=feQMi1", "DATA PROCESO ELECTORAL"),
    new Documents("2022","Segunda Vuelta","Elección de Presidente y Vicepresidente", "29 de junio", "https://registraduriaco.sharepoint.com/:b:/s/DireccindeGestinElectoral209/EdER1-WGQHpMtCikZWFtlrwBFWbJcN7vnaw8CQ2uLNxTdA?e=pef4zw", "ACTA GENERAL DEL ESCRUTINIO (AGE)", "https://registraduriaco.sharepoint.com/:b:/s/DireccindeGestinElectoral209/ERJjblt82wpHo3fMYKdzt3wBdCuYaAqZwFor1RaEEZ496A?e=Nn5heS", "ACTA DEL ESCRUTINIO GENERAL (E-26)", "https://registraduriaco.sharepoint.com/:b:/s/DireccindeGestinElectoral209/EQqWWjF6Rf5Ev6jH2AiKab0Bri7g41kz2Qp93AYwaGsI-Q?e=gMIH4g", "RESULTADOS DEL ESCRUTIONO (E-24)", "", "-", "https://registraduriaco.sharepoint.com/:x:/s/DireccindeGestinElectoral209/EW4SfksUAR9Pqa55ldX2i2YBB1MtZniUlr9oSwFe8xxXNg?e=feQMi1", "DATA PROCESO ELECTORAL"),
    new Documents("2022","Segunda Vuelta","Elección de Presidente y Vicepresidente", "29 de junio", "https://registraduriaco.sharepoint.com/:b:/s/DireccindeGestinElectoral209/EdER1-WGQHpMtCikZWFtlrwBFWbJcN7vnaw8CQ2uLNxTdA?e=pef4zw", "ACTA GENERAL DEL ESCRUTINIO (AGE)", "https://registraduriaco.sharepoint.com/:b:/s/DireccindeGestinElectoral209/ERJjblt82wpHo3fMYKdzt3wBdCuYaAqZwFor1RaEEZ496A?e=Nn5heS", "ACTA DEL ESCRUTINIO GENERAL (E-26)", "https://registraduriaco.sharepoint.com/:b:/s/DireccindeGestinElectoral209/EQqWWjF6Rf5Ev6jH2AiKab0Bri7g41kz2Qp93AYwaGsI-Q?e=gMIH4g", "RESULTADOS DEL ESCRUTIONO (E-24)", "", "-", "https://registraduriaco.sharepoint.com/:x:/s/DireccindeGestinElectoral209/EW4SfksUAR9Pqa55ldX2i2YBB1MtZniUlr9oSwFe8xxXNg?e=feQMi1", "DATA PROCESO ELECTORAL"),
    new Documents("2022","Segunda Vuelta","Elección de Presidente y Vicepresidente", "29 de junio", "https://registraduriaco.sharepoint.com/:b:/s/DireccindeGestinElectoral209/EdER1-WGQHpMtCikZWFtlrwBFWbJcN7vnaw8CQ2uLNxTdA?e=pef4zw", "ACTA GENERAL DEL ESCRUTINIO (AGE)", "https://registraduriaco.sharepoint.com/:b:/s/DireccindeGestinElectoral209/ERJjblt82wpHo3fMYKdzt3wBdCuYaAqZwFor1RaEEZ496A?e=Nn5heS", "ACTA DEL ESCRUTINIO GENERAL (E-26)", "https://registraduriaco.sharepoint.com/:b:/s/DireccindeGestinElectoral209/EQqWWjF6Rf5Ev6jH2AiKab0Bri7g41kz2Qp93AYwaGsI-Q?e=gMIH4g", "RESULTADOS DEL ESCRUTIONO (E-24)", "", "-", "https://registraduriaco.sharepoint.com/:x:/s/DireccindeGestinElectoral209/EW4SfksUAR9Pqa55ldX2i2YBB1MtZniUlr9oSwFe8xxXNg?e=feQMi1", "DATA PROCESO ELECTORAL")
  ];

  //Crear el objeto para nivel departamental
}
